baseurl = "https://yoolc.github.io"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
theme = "terminal"

[paginator]
pagetSize = 5

[markup.goldmark.renderer]
unsafe = true

[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['$', '$']]

[params]
math = true
contentTypeName = "posts"
showMenuItems = 4
fullWidthTheme = false
centerTheme = true
keywords = "computer architecture, free and open source software"
subtitle = "A tiny hugo blogsite for some intresting idea"
menuMore = "æ›´å¤š"
readMore = "é˜…è¯»æ›´å¤š"
readOtherPosts = "é˜…è¯»å…¶ä»–æ–‡ç« "
[params.logo]
logoText = "YooLc.github.io"
logoHomeLink = "/"

[languages]
[languages.zh-cn]
title = "YooLc.github.io"
copyright = ""

[languages.zh-cn.menu]
[[languages.zh-cn.menu.main]]
identifier = "system"
name = "ğŸ’» è®¡ç®—æœºç³»ç»Ÿ"
url = "/posts/system"
[[languages.zh-cn.menu.main]]
identifier = "foss"
name = "ğŸº è‡ªç”±å¼€æºè½¯ä»¶"
url = "/posts/foss"
[[languages.zh-cn.menu.main]]
identifier = "about"
name = "å…³äº"
url = "/about"
